### ISSUE TITLE
Extension stopped working

### ISSUE THREAD

**Issue by Jarek911** [rsimmons/subadub#12]
Extension stopped working alltogether - a few days ago subtitles for this episode were fine, but now you cannot select any language from dropdown:
![image](https://user-images.githubusercontent.com/5693464/69988863-c24be500-1542-11ea-979e-ebb11230b3ab.png)
Maybe there was some update on Netflix side which causes the addon to malfuction?

Tested on newest version of Chrome, Brave and Firefox.

**Comment by weirdalsuperfan** [comment]
Same, just noticed this....

**Comment by rsimmons** [comment]
Thanks, I will take a look as soon as I can. I assume there was an update on the Netflix side.

**Comment by rsimmons** [comment]
Bad news, it looks like Netflix may have made a change that doesn't allow any workaround.

A little background: For Japanese (and some other languages), Netflix fetches the subtitles from the servers as images, not text. We obviously want them as text so we can use popup dictionaries, cut and paste, etc. Someone noticed that Netflix _does_ actually have them as text, but just doesn't usually use the text versions. The text version were under the format name `webvtt-lssdh-ios8`, which makes it look like it was a legacy thing to support old iOS versions. Subadub worked by fetching these. It appears that Netflix no longer serves them, which is not a big surprise, I assume they updated all their clients to use the image ones. So unfortunately there is no easy workaround for Subadub.

The only way to work around this would be to use OCR, which is much more complicated, and outside of the scope of work I can take on right now. Current open source OCR libraries tend to produce a ton of mistakes in their output. With the recent advances in deep learning, it would be a good time for someone to make a new and awesome OCR library that could be applied to this task.

**Comment by David11213** [comment]
@rsimmon
The subtitles still exist in webvtt-lssdh-ios8 format in Netflix (not sure what changed for the web interface in the browsers) and the plugin.video.netflix is still using the webvtt-lssdh-ios8 format to show the subtitles, may be you will need to modify subadub to download the subtitles not using the browsers in webvtt-lssdh-ios8 format then converting them to srt and upload the subtitles to subadub.

https://github.com/asciidisco/plugin.video.netflix/releases

you can download this modified version of the add-on which can download the subtitles in webvtt-lssdh-ios8 format and converting them to srt format, you could look inside MSLv2.py to see how it works

https://mega.nz/#!B9dlzSiZ!A8iTDnSH2ILv_KuXioiHnKE0TcCSc6XyNs-zEFRMRp0

this video shows how it install and use it

https://mega.nz/#!Z4tERAZB!tzvavugHC4QYxIOnmPivvkHrIanUH0LpOecubfe15yg

**Comment by rsimmons** [comment]
It seems to have magically started working again. Can one of you confirm?

**Comment by askoufis** [comment]
Not working for me yet in either chrome or firefox. Whatever change netflix have made could be gradually rolling out, so it's worth waiting a few hours/days before confirming anything.

**Comment by E1219** [comment]
In Netflix if you turned this switch off subadub will work, someone found this solution to another script and I tested it with subadub on Google chrome and it worked.

https://www.netflix.com/DoNotTest

**Comment by MarkForsythe** [comment]
> In Netflix if you turned this switch off subadub will work, someone found this solution to another script and I tested it with subadub on Google chrome and it worked.
> 
> https://www.netflix.com/DoNotTest

This didn't work for me. If anyone finds any other workarounds I would very much like to hear about it.

**Comment by mwhirls** [comment]
Hey folks, I think I figured out a solution to the issue.  It's not necessarily that Netflix has stopped supporting their WebVTT (text-based) subtitle formats for Japanese, it's that the extension is failing to properly request the format now.  This appears to be because Netflix recently updated some of their JSON manifest object layouts.

I don't have permissions to push up a branch for a pull request, so I'll just paste the changes here.  I was able to get things working by changing this bit of code:
```
  const originalStringify = JSON.stringify;
  JSON.stringify = function(value) {
    if (value && value.params && value.params.profiles) {
      value.params.profiles.unshift(WEBVTT_FMT);
      // console.log('stringify', value);
    }
    return originalStringify.apply(this, arguments);
  };
```
to this:
```
  const originalStringify = JSON.stringify;
  JSON.stringify = function(value) {
    if (value && value.params && value.params.profiles) {
      value.params.profiles.unshift(WEBVTT_FMT);
      // console.log('stringify', value);
    }
    if (value && value.ab && value.ab.profiles) {
      value.ab.profiles.unshift(WEBVTT_FMT);
    }
    return originalStringify.apply(this, arguments);
  };
```
The profiles list (which is basically the subtitles we're requesting) is now located at `ab` instead of `params`.  I left the older one in just in case we need to maintain support.  When I tested in Google Chrome, things came back online, but I didn't give Firefox a shot.

@rsimmons Let me know if this works for you!

**Comment by Justincain50** [comment]
I downloaded the "Learn Language With Netflix" Chrome extension and still had Subadub on and magically the text subs were back. It wasn't the LLN style subs it was the way Subadub does it (Could even select from the dropdown menu). I don't know if it's because Subadub is being worked on or what, but it only happens when i'm using LLN. 

Based on that I assume the text subs are still available, although I don't know why having LLN on makes Subadub work.

**Comment by E1219** [comment]
@mwhirls
Thank you so much, tested on Google chrome and Firefox and it worked.

**Comment by rsimmons** [comment]
Thanks for the fix @mwhirls! I had been away from the code for so long that I forgot that it injects that change in the request.

I uploaded a new version (0.1.4) with the fix for both Chrome and Firefox. The Firefox one is now live, the Chrome one is still waiting for approval. When that goes through and I test it, I will close out this issue.

**Comment by rsimmons** [comment]
The Chrome Web Store has accepted the new version, so I'll close this now. Thanks for the help everyone.

**Comment by josueJURE** [comment]
Hi, 

I’ve recently started using the browser extension Subadub. But when I click on Download SRT and then click on the file to open it I’m getting:

1-There is no application set to open the document “70045021_ja (2).srt”.

2-Search the App Store for an application that can open this document, or choose an existing application on your computer.

But when I search the App Store the following message pops up: "App Not Available. This app is currently not available in your country or region".

What application/existing application on my computer should I use? I’m a Mac user as you might have guessed.

**Comment by rsimmons** [comment]
Hi @josueJURE, I don't think your problem has anything to do with Subadub. But on a Mac, you can use TextEdit (or any other text editor) to open SRT files.

**Comment by BigUncleKerch** [comment]
@rsimmons Hi I'm having the same issue today where I can't select any language from the drop down box. It was working for me last week but not anymore.

**Comment by rsimmons** [comment]
> @rsimmons Hi I'm having the same issue today where I can't select any language from the drop down box. It was working for me last week but not anymore.

Thanks for letting me know. It's also broken for me. I'm looking into it now.

**Comment by rsimmons** [comment]
A new version 0.1.9 has been uploaded for Chrome and Firefox that should fix this.

**Comment by BigUncleKerch** [comment]
> A new version 0.1.9 has been uploaded for Chrome and Firefox that should fix this.

@rsimmons thank you Russ for fixing it so quickly!
